baseURL = "http://localhost/"
title = "Pathogens Portal"
theme = "hugo-pathogens-portal"

# (Optional) Set this to true to enable 'Last Modified by' date and git author
#  information on 'doc' type pages.
# enableGitInfo = true

# Specify the default content language.
defaultContentLanguage = "en"

# Multilingual mode config
# There are different options to translate files
# See https://gohugo.io/content-management/multilingual/#translation-by-filename
# And https://gohugo.io/content-management/multilingual/#translation-by-content-directory
# [languages]
# [languages.en]
# languageName = "English"
# languageCode = "en"
# contentDir = "content"
# weight = 1

[params]
# (Optional) Set source repository location.
# Used for 'Last Modified' and 'Edit this page' links.
# repository = "https://github.com/sib-swiss/hugo-pathogens-portal"

# (Optional) Enable 'Edit this page' links for 'doc' page type.
# Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
# Path must point to the site directory.
# editPath = 'edit/main/exampleSite'

# (Optional) Set the logo for your institution next to the pathogens-portal logo.
# logo = "images/logo.png"

# (Optional) Set the external link for the logo of your institution.
# homepage = "https://www.google.com"

# (Optional) Set the email to contact you
# mail = ""

# (Optional) Set the social media links for your institution.
# twitter = ""
# linkedin = ""

# (Optional) Set the country to retrieve stats from the central pathogens-portal.
# This is used to retrive several stats from the central pathogens-portal using the API
# and filtering by your configured country.
# country = "Switzerland"

# (Optional) Set the country to retrieve publications from the Europe PMC API.
# This is used to retrieve publications from the Europe PMC API and filtering by your configured country.
# pubmed_country = "Switzerland"

# (Optional) Set the URL of your national biobank to display the link on the homepage.
# biobank_url = ""
